# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae6443a6ebf2f9950373ad633d44b10c17a2bcc84fc6256ced917e9e7cb530e8530b1e7a04276ff32961cb0606a36609620c58dbc8ec8b6bb62828a9b67037cf

test:
  secret_key_base: b1161aaeb9f6d143906628f1632a6345618e9166358b44a20256436d40f837be4972644f67db5d8a2aa97ce7272626fdae584635bc8f9097c4441995c08566ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
